LANGUAGES = {
    'en': {
        'username': 'Enter your name⬇:',
        'greeting': 'Hi, *{username}*, I\'m glad to see you here. Let\'s get started🤗. Use /help command.',
        'help': 'Here is the list of available commands:\n/learn - start learning\
                                                                    \n/tutor - instructions for using this bot\
                                                                    \n/config - configure vocabulary test cases\
                                                                    \n/info - additional information about the developer and other tg-products',
        'config': '*Configuration menu*\nAdd new features and edit old ones!',
        'config_language': '*Choose your language*',
        'config_username': 'Enter the new username⬇:',
        'config_new_username': 'Hi, *{username}*!',
        'tutor_photo': 'The main thing you should follow is the input data. Just use the *"only word and its translation"* rule to get your test right, in the other cases you will receive an error-message that doesn’t allow you to implement the test😕',
        'tutor_video': '*Video explanation🎬*',
        'cancel_empty': 'There is nothing to cancel🤓',
        'cancel': 'Operation canceled❌',
        'learn_dict_create': '*Dictionary constructor*🧩\n\nFollow this example to fill in the dictionary, do it with one message:\n\n*diligent старанний\ninheritance спадок\nconvenient зручний*\n\nIf you are not sure you can do it correctly, please, use the /tutor command.\nYou are also able to cancel this operation, just click on the *CANCEL* button',
        'learn_pass_words': 'Enter the words and their translations, I am ready to receive them🗂',
        'learn_invalid_value': 'Invalid value😩\nTry once more, or check out /tutor command',
        'complete_dict': 'Your dictionary is complete. Press \"READY\" to start🏆',
        'learn_start': 'The test is started!',
        'learn_error': 'Oops, something went wrong😬, try again later',
        'test_right': 'Right✅',
        'test_wrong': 'Wrong❌',
        'test_wrong_second': 'Wrong! I will include this word into the next round\nThe correct answer was: *{word}*',
        'right_test_result': 'The test completed with *{result}%* of correct answers! Keep it up!😤',
        'wrong_test_result': 'The ***first round*** is over with *{resik}%* of correct answers!🏁\nThe second one will include *{lenka}* words. Shall we start? You\'ll handle it!💪',
        'second_test_complete': 'The *second round* is complete! Well done!🎊',
        'canceled_test': 'The test is canceled, but don\'t forget repeat these words:\n\n*{res}*\n\nGood luck!🏆',
        'canceled_test2': 'The test is canceled, but don\'t forget repeat these words:\n\n*{res1k}*\n\nGood luck!🏆',
        'insert_error': 'Oops, something went wrong😬, try again later',
        'information': '<b>Project developer: @vladakawalet\n<a href="https://t.me/testpadsource">Our telegram-channel</a></b>',
        'primarykey_err': '*{username}*, you already have an account. If you want to change its settings, use /congfig command',
    },  
    'uk': {
        'username': 'Введіть своє ім\'я⬇:',
        'greeting': 'Привіт, *{username}*, я радий бачити тебе тут. Давай розпочнемо🤗. Тисни на команду /help',
        'help': 'Ось список доступних команд:\n/learn - почати навчання\
                                                                \n/tutor - інструкція з використання бота\
                                                                \n/config - редагувати навчальний процес\
                                                                \n/info - додаткова інформація про розробника й інші tg-проєкти',
        'config': '*Меню конфігурації*\nДодавай нові функції і редагуйте старі!',
        'config_language': '*Виберіть свою мову*',
        'config_username': 'Введіть нове ім\'я користувача⬇:',
        'config_new_username': 'Привіт, *{username}*!',
        'tutor_photo': 'Найголовніша річ, яку тобі слід пильнувати, - це вхідні дані. Просто дотримуйся правила *"одне слово і його переклад"*, щоб створити правильний тест. У інших випадках ти отримаєш повідомлення про помилку, яке не дозволить пройти тест😕',
        'tutor_video': '*Відео пояснення*🎬',
        'cancel_empty': 'Немає що скасовувати🤓',
        'cancel': 'Операція скасована❌',
        'learn_dict_create': '*Конструктор словника*🧩\n\nЗаповнюй словник, як показано у цьому прикладі, зроби це одним повідомленням:\n\n*diligent старанний\ninheritance спадок\nconvenient зручний*\n\nЯкщо ти не впевнений(-а), що зможеш зробити це правильно, будь ласка, викорстай команду /tutor.\nТи також можеш скасувати цю операцію, просто натисни кнопку *СКАСУВАТИ*',
        'learn_pass_words': 'Введи слова і їх переклад, я готовий їх отримати🗂',
        'learn_invalid_value': 'Невірне значення😩\nСпробуй ще раз, або переглянь команду\n/tutor',
        'complete_dict': 'Твій словник готовий, тисни \"READY\", щоб почати',
        'learn_start': 'Тест розпочато!',
        'learn_error': 'Ой, щось пішло не так😬, спробуй ще раз пізніше',
        'test_right': 'Правильно✅',
        'test_wrong': 'Невірно❌',
        'test_wrong_second': 'Невірно! Додаю це слово у наступний раунд\nПравильна відповідь: *{word}*',
        'right_test_result': 'Тест завершено з *{result}%* відсотками правильних відповідей. Так тримати!😤',
        'wrong_test_result': '***Перший раунд*** завершено з *{resik}%* відсотками правильних відповідей!🏁\nДругий буде включати в себе *{lenka}* слів. Розпочнемо? Ти справишся!💪',
        'second_test_complete': '*Другий раунд* завершено! Красава!🎊',
        'canceled_test': 'Тест скасовано, проте не забудь повторити ці слова:\n\n*{res}*\n\nНехай щастить!🏆',
        'canceled_test2': 'Тест скасовано, проте не забудь повторити ці слова:\n\n*{res1k}*\n\nНехай щастить!🏆',
        'insert_error': 'Ой, щось пішло не так😬, спробуй ще раз пізніше',
        'information': '<b>Розробник проєкту: @vladakawalet\n<a href="https://t.me/testpadsource">Наш телеграм-канал</a></b>',
        'primarykey_err': '*{username}*, ти вже зареєстрований. Якщо хочеш змінити налаштування - використовуй команду /config',

    }
}