"""final

Revision ID: faf43c2e3dae
Revises: 0c7b1ad5b017
Create Date: 2024-01-25 19:53:31.761303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'faf43c2e3dae'
down_revision: Union[str, None] = '0c7b1ad5b017'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'language',
               existing_type=sa.VARCHAR(length=2),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'language',
               existing_type=sa.VARCHAR(length=2),
               nullable=True)
    # ### end Alembic commands ###
